"""initial migration

Revision ID: 96538496a01e
Revises: 
Create Date: 2026-06-30 16:44:12.964826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96538496a01e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advance_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advance_number', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_type', sa.Enum('CASH', 'BANK', 'CHEQUE', 'ONLINE', name='paymenttype'), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'CANCELLED', name='advancepaymentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'advance_number', name='uq_advance_tenant_number')
    )
    with op.batch_alter_table('advance_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advance_payments_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('advance_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advance_payments_tenant_id'))

    op.drop_table('advance_payments')
    # ### end Alembic commands ###
